{
    "Id": 2326413,
    "NegotiatorId": null,
    "Name": "DIRECT LOANS",
    "CustomerId": 3739081,
    "Comments": "",
    "AccountNumber": "31045169",
    "OriginalBalance": 7818,
    "CurrentBalance": 0,
    "CreditorStatusId": 18,
    "AccountHolderId": 1,
    "DateAdded": "2025-01-10T20:54:30Z",
    "IsPOA": false,
    "PoaAutomation": null,
    "PoaSentDate": null,
    "DateUpdated": null,
    "IsLawSuit": false,
    "EgAttorney": null,
    "AttorneyName": null,
    "IsSettlementSetup": false,
    "IsSettlementApproved": false,
    "SettlementStatusId": 0,
    "SettlementId": 0,
    "SettlementRequestDate": null,
    "LastPaymentDate": null,
    "CurrentCreditorName": "US DEPARTMENT OF EDU",
    "CurrentCreditorBalance": 0,
    "CurrentCreditorAccountNumber": "",
    "SettlementRequestedUserId": 0,
    "AccountTypeId": 14,
    "MonthlyPayment": 0,
    "CreatedUserId": 2153,
    "SettledUserId": 0,
    "Delinquent3Years": false,
    "Offer": null,
    "Fee": null,
    "Note": "",
    "ClearedFeePerc": null,
    "ClearedPaymentPerc": null,
    "SettlementRequestedUser": {
    "Id": 0,
        "Name": ""
},
    "NegotiationPhase": {
    "Id": 0,
        "Name": ""
},
    "CreditorAccountHolder": {
    "Id": 1,
        "Name": "Applicant"
},
    "CreditorAccountType": {
    "Id": 14,
        "Name": "Student Loan"
},
    "TermSettlement": {
    "IsTermSettlement": false,
        "TermSettlementStartDate": "0001-01-01T00:00:00",
        "TermSettlementEndDate": "0001-01-01T00:00:00"
}
}